version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 176087999103.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=176087999103.dkr.ecr.ap-south-1.amazonaws.com/portfolio
      - IMAGE_TAG=latest

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
